config/routes.rb
Rails.application.routes.draw do
  root 'front_pages#home'

  get 'about', to: 'front_pages#about', as: :about

  get   '/register',  to: 'registrations#new',    as: :registration
  post  '/register',  to: 'registrations#create', as: :registration_create

  get '/login',                   to: 'sessions#new',                 as: :login
  post '/login',                  to: 'sessions#create',              as: :login_create
  delete 'logout',                to: 'sessions#destroy',             as: :logout
  delete 'logout_all_sessions',   to: 'sessions#destroy_from_all',    as: :logout_all

  # resources :password_resets,     only: [:new, :create, :edit, :update]
  get   'password_reset',     to: 'password_resets#new',            as: :password_reset
  post  'password_reset',     to: 'password_resets#create'
  get   'reset_token',        to: 'password_resets#enter_token',           as: :password_reset_token
  get   'reset_token/:token', to: 'password_resets#submit_token_from_email', as: :password_reset_token_from_email
  post  'reset_token',        to: 'password_resets#submit_token'
  patch 'password_reset',     to: 'password_resets#reset_password'

  get '/users/:username', to: 'users#show', as: :users_show
  get '/users/:username/edit', to: 'users#edit', as: :users_edit
  patch '/users/:username/update', to: 'users#update', as: :users_update
  get '/users/:username/change_password', to: 'users#change_password', as: :users_change_password
  patch '/users/:username/change_password', to: 'users#update_password', as: :users_update_password

  get 'dashboard', to: 'dashboards#show', as: :dashboard
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :logged_in_user
  before_action      :guest_user_only
  skip_after_action  :verify_authorized

  def new; end

  def create
    @user = user_to_recover(params[:password_reset][:username].downcase)
    if @user
      @user.create_password_reset_token
      UserMailer.password_reset_email(@user).deliver_later
      flash[:info] = 'Email sent with password reset instructions to your primary email address'
      redirect_to root_url
    else
      flash.now[:danger] = 'Incorrect details entered'
      render 'new'
    end
  end

  def enter_token
    @user = User.new
  end

  def submit_token
    validate_token(password_reset_token: params[:user][:password_reset_token])
  end

  def submit_token_from_email
    validate_token(password_reset_token: params[:token])
  end

  def reset_password
    @user = User.find_by(password_reset_token: params[:password_reset_token])
    if params[:user][:password].blank?
      @user.errors.add(:password, 'must be entered')
      render 'reset_password'
    elsif @user.update_attributes(user_update_password_params)
      valid_password_change
    else
      render 'reset_password'
    end
  end

  private

  def validate_token(token)
    @user = User.find_by(token)
    if @user
      flash.now[:info] = 'Token valid'
      render 'reset_password'
    else
      flash.now[:danger] = 'Token not found'
      @user = User.new
      render 'enter_token'
    end
  end

  def valid_password_change
    @user.forget_all_remember_tokens
    UserMailer.password_reset_successful_email(@user).deliver_later
    flash[:success] = 'Password changed'
    redirect_to root_path
  end

  def user_update_password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def user_to_recover(credential)
    if /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i =~ credential
      EmailAddress.find_by(email_address: credential).user
    else
      User.find_by(username: credential.downcase)
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/enter_token.html.erb
<% provide(:title, 'Reset password') %>
<h1>Password reset</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_token_path) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :password_reset_token %>
        <%= f.text_field :password_reset_token, class: 'form-control' %>

        <%= f.submit 'Submit Token', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password") %>
<h1>Forgot password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_reset_path) do |f| %>
        <%= f.label :username, 'Username or Password' %>
        <%= f.text_field :username, class: 'form-control' %>

        <%= f.submit 'Request Password Reset', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/password_resets/reset_password.html.erb
<% provide(:title, 'Reset password') %>
<h1>Password reset</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= hidden_field_tag :password_reset_token, @user.password_reset_token %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>