config/routes.rb
Rails.application.routes.draw do
  root 'front_pages#home'

  get 'about', to: 'front_pages#about', as: :about

  get   '/register',  to: 'registrations#new',    as: :registration
  post  '/register',  to: 'registrations#create', as: :registration_create

  get '/login',                   to: 'sessions#new',                 as: :login
  post '/login',                  to: 'sessions#create',              as: :login_create
  delete 'logout',                to: 'sessions#destroy',             as: :logout
  delete 'logout_all_sessions',   to: 'sessions#destroy_from_all',    as: :logout_all

  # resources :password_resets,     only: [:new, :create, :edit, :update]
  get   'password_reset',     to: 'password_resets#new',            as: :password_reset
  post  'password_reset',     to: 'password_resets#create'
  get   'reset_token',        to: 'password_resets#enter_token',           as: :password_reset_token
  get   'reset_token/:token', to: 'password_resets#submit_token_from_email', as: :password_reset_token_from_email
  post  'reset_token',        to: 'password_resets#submit_token'
  patch 'password_reset',     to: 'password_resets#reset_password'

  get '/users/:username', to: 'users#show', as: :users_show
  get '/users/:username/edit', to: 'users#edit', as: :users_edit
  patch '/users/:username/update', to: 'users#update', as: :users_update
  get '/users/:username/change_password', to: 'users#change_password', as: :users_change_password
  patch '/users/:username/change_password', to: 'users#update_password', as: :users_update_password

  get 'dashboard', to: 'dashboards#show', as: :dashboard
end

app/models/user.rb
class User < ApplicationRecord
  VALID_USERNAME_REGEX = /\A[a-zA-Z0-9\_\-]+\z/

  validates :first_name,  presence: true
  validates :last_name,   presence: true
  validates :username,    presence: true,
                          format: { with: VALID_USERNAME_REGEX },
                          uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  has_many :user_remember_tokens
  has_many :email_addresses, inverse_of: :user

  accepts_nested_attributes_for :email_addresses

  class << self
    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def primary_email
    email_addresses.find_by(primary: true)
  end

  def remember
    token = UserRememberToken.new(user: self, remember_digest: User.new_token)
    self.user_remember_tokens << token
    token.remember_digest
  end

  def remembered_by_token?(token)
    UserRememberToken.find_by(user: self.id, remember_digest: token)
  end

  # Forgets a user.
  def forget_remember_token(token)
    UserRememberToken.where(remember_digest: token, user: self).destroy_all
  end

  def forget_all_remember_tokens
    UserRememberToken.where(user: self).destroy_all
  end

  def create_password_reset_token
    update_attributes(password_reset_token: SecureRandom.urlsafe_base64, password_reset_token_at: Time.zone.now)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(username: params[:username])
    authorize @user
  end

  def edit
    @user = User.find_by(username: params[:username])
    authorize @user
  end

  def update
    @user = User.find_by(username: params[:username])
    authorize @user
    if @user.update_attributes(user_update_params)
      flash[:success] = 'Profile updated'
      redirect_to users_show_path(username: @user.username)
    else
      render 'edit'
    end
  end

  def change_password
    @user = User.find_by(username: params[:username])
    authorize @user
  end

  def update_password
    @user = User.find_by(username: params[:username])
    authorize @user
    if @user.authenticate(params[:user][:current_password])
      correct_user_password_change
    else
      @user.errors.add(:current_password, 'is incorrect')
      render 'change_password'
    end
  end

  private

  def user_update_params
    params.require(:user).permit(:first_name, :last_name, :location)
  end

  def user_update_password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def correct_user_password_change
    if params[:user][:password].blank?
      @user.errors.add(:password, 'must be entered')
      render 'change_password'
    elsif @user.update_attributes(user_update_password_params)
      UserMailer.changed_password_email(@user.primary_email).deliver_later
      flash[:success] = 'Password changed'
      redirect_to users_show_path(username: @user.username)
    else
      render 'change_password'
    end
  end
end

app/views/users/change_password.html.erb
<% provide(:title, 'Change Password') %>


<div class="row">
  <%= render 'users/shared/user_side_menu' %>
  <div class="col-md-9">
    <h2 class="subheader">Update your password</h2>
    <%= form_for(@user, url: users_update_password_path) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :current_password %>
        <%= f.password_field :current_password, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, 'Password confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit 'Change Password', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<div class="row">
  <%= render 'users/shared/user_side_menu' %>
  <div class="col-md-9">
    <h2 class="subheader">Update your profile</h2>
    <%= form_for(@user, url: users_update_path) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>

        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>

        <%= f.label :location %>
        <%= f.text_field :location, class: 'form-control' %>


        <%= f.submit 'Update Profile', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<% if @user.location %>
  <p>Location: <%= @user.location %></p>
<% end %>