config/routes.rb
Rails.application.routes.draw do
  root 'front_pages#home'

  get 'about', to: 'front_pages#about', as: :about

  get   '/register',  to: 'registrations#new',    as: :registration
  post  '/register',  to: 'registrations#create', as: :registration_create

  get '/login',                   to: 'sessions#new',                 as: :login
  post '/login',                  to: 'sessions#create',              as: :login_create
  delete 'logout',                to: 'sessions#destroy',             as: :logout
  delete 'logout_all_sessions',   to: 'sessions#destroy_from_all',    as: :logout_all

  # resources :password_resets,     only: [:new, :create, :edit, :update]
  get   'password_reset',     to: 'password_resets#new',            as: :password_reset
  post  'password_reset',     to: 'password_resets#create'
  get   'reset_token',        to: 'password_resets#enter_token',           as: :password_reset_token
  get   'reset_token/:token', to: 'password_resets#submit_token_from_email', as: :password_reset_token_from_email
  post  'reset_token',        to: 'password_resets#submit_token'
  patch 'password_reset',     to: 'password_resets#reset_password'

  get '/users/:username', to: 'users#show', as: :users_show
  get '/users/:username/edit', to: 'users#edit', as: :users_edit
  patch '/users/:username/update', to: 'users#update', as: :users_update
  get '/users/:username/change_password', to: 'users#change_password', as: :users_change_password
  patch '/users/:username/change_password', to: 'users#update_password', as: :users_update_password

  get 'dashboard', to: 'dashboards#show', as: :dashboard
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  include SessionsHelper

  before_action :logged_in_user

  after_action :verify_authorized
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def logged_in_user
    return if logged_in?
    store_location
    flash[:danger] = 'You are not logged in'
    redirect_to login_url
  end

  def guest_user_only
    return unless logged_in?
    flash[:info] = 'You are already logged in'
    redirect_to root_url
  end

  def user_not_authorized
    flash[:danger] = 'You do not have the authorization to do that'
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = 'Floworx SysArch'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end

  def active_action?(action_name)
    params[:action] == action_name ? 'active' : nil
  end
end

app/views/layouts/application/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'Floworx SysArch', root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li><%= link_to 'Edit Profile', users_edit_path(username: current_user.username) %></li>
            <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            <li><%= link_to 'Log out from all computers', logout_all_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Register', registration_path %></li>
          <li><%= link_to 'Log in', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>